linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gofmt:
    simplify: false
  gocyclo:
    min-complexity: 20
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  goimports:
    local-prefixes: git.6740.io/scottshotgg/qemu-api

linters:
  disable-all: true
  enable:
  - unused
  - goimports
  - typecheck
  - ineffassign
  - govet
  - errcheck
  - revive
  - gosec
  - unconvert
  - goconst
  - gocyclo
  - gofmt
  - misspell
  - prealloc

  # enable:
  #   - errcheck
  #   - gosimple
  #   - govet
  #   - ineffassign
  #   - staticcheck
  #   - typecheck
  #   - unused
  #   - asasalint
  #   - asciicheck
  #   - bidichk
  #   - bodyclose
  #   - containedctx
  #   - contextcheck
  #   - cyclop
  #   - decorder
  #   - depguard
  #   - dogsled
  #   - dupl
  #   - durationcheck
  #   - errchkjson
  #   - errname
  #   - errorlint
  #   - execinquery
  #   - exhaustive
  #   - exhaustruct
  #   - exportloopref
  #   - forbidigo
  #   - forcetypeassert
  #   - funlen
  #   - gci
  #   - gochecknoglobals
  #   - gochecknoinits
  #   - gocognit
  #   - goconst
  #   - gocritic
  #   - gocyclo
  #   - godot
  #   - godox
  #   - goerr113
  #   - gofmt
  #   - gofumpt
  #   - goheader
  #   - goimports
  #   - gomnd
  #   - gomoddirectives
  #   - gomodguard
  #   - goprintffuncname
  #   - gosec
  #   - grouper
  #   - importas
  #   - interfacebloat
  #   - ireturn
  #   - lll
  #   - logrlint
  #   - maintidx
  #   - makezero
  #   - misspell
  #   - nakedret
  #   - nestif
  #   - nilerr
  #   - nilnil
  #   - nlreturn
  #   - noctx
  #   - nolintlint
  #   - nonamedreturns
  #   - nosprintfhostport
  #   - paralleltest
  #   - prealloc
  #   - predeclared
  #   - promlinter
  #   - reassign
  #   - revive
  #   - rowserrcheck
  #   - sqlclosecheck
  #   - stylecheck
  #   - tagliatelle
  #   - tenv
  #   - testpackage
  #   - thelper
  #   - tparallel
  #   - unconvert
  #   - unparam
  #   - usestdlibvars
  #   - varnamelen
  #   - wastedassign
  #   - whitespace
  #   - wrapcheck
  #   - wsl

issues:
  exclude-files: 
    - ".gitignore"
    - ".golangci.yaml"
    - "docker-compose.yaml"
    - "go.mod"
    - "go.sum"
    - "Makefile"
    - "README.md"
    - "VERSION"
  exclude-dirs:
  - ".git"
  - "vendor"
  - ".circleci"
  - ".vscode"
  - "docs"
  - "assets"
  - "deploy"
  exclude:
  - "should have a package comment, unless it's in another file for this package"
  - "should have comment or be unexported"
  - "should have a package comment"
  #   - "should not use basic type string as key in context.WithValue"
  #   - "type `DeviceXMlModel` should be `DeviceXMLModel`"
  #   - "should have comment"
  #   - "that stutters"
  #   - "is unused"
  exclude-use-default: false
  max-same-issues: 0

run:
  allow-parallel-runners: true
  go: "1.22"
  tests: false